apiVersion: v1
kind: Pod
metadata:
  name: mysql-db
  labels:
    app: mysql
spec:
  containers:
    - image: mysql
      name: mysql-container
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: mysql-config
